### ISSUE TITLE
🐛 fix: Error: Unable to connect to the database.

### ISSUE THREAD

**Issue by nuyeo** [Kakao-Groomton-MusicGen/Back-End#1]
# Title

- error: no pg_hba.conf entry for host "211.244.225.211", user "postgres", database "music_gen", no encryption
    at Parser.parseErrorMessage (/Users/nunu/Desktop/dev/kakao-bootcamp/groomthon/groomthon-be/node_modules/pg-protocol/src/parser.ts:369:69)
![image](https://github.com/user-attachments/assets/92254b07-f22b-4296-8886-78978d3b097b)

# TODO

- [x] RDS 보안 그룹에서 백엔드 서버의 IP를 허용하도록 설정
- [x] PostgreSQL의 SSL 설정이 강제된 경우, TypeORM 설정에 SSL 옵션 추가
- [x] 올바른 환경 변수가 사용되고 있는지 확인

# 문제 원인
pg_hba.conf는 PostgreSQL의 인증을 관리하는 파일로, 외부 IP 주소가 데이터베이스에 접근할 수 있는지 정의합니다.
메시지에서 pg_hba.conf entry for host "211.244.225.211"라고 되어 있는데, 이는 RDS가 해당 IP의 접근을 허용하지 않는다는 의미입니다.
또한, 해당 오류는 암호화되지 않은 연결(SSL 없이)을 시도했기 때문에 발생할 수 있습니다.

# 해결 방법
### 1. RDS 보안 그룹 설정 확인
AWS RDS 보안 그룹에서 해당 데이터베이스에 접근할 수 있는 IP 또는 IP 범위를 허용해야 합니다.
AWS 콘솔에서 RDS 인스턴스를 선택하고, 보안 그룹을 확인합니다.
보안 그룹의 인바운드 규칙에 백엔드 서버의 IP를 추가합니다. 일반적으로 포트는 5432입니다.
### 2. PostgreSQL 설정 확인
PostgreSQL RDS의 경우 직접적으로 pg_hba.conf 파일을 수정할 수 없으므로, RDS 인스턴스의 파라미터 그룹을 설정하여 연결 정책을 관리합니다.
만약 RDS에서 SSL을 강제하는 설정이 되어 있다면, 백엔드에서 SSL 연결을 사용해야 합니다.
### 3. TypeORM SSL 설정 적용
만약 RDS가 SSL을 강제하고 있다면, TypeORM 설정에서 SSL 옵션을 추가해야 합니다.

## app.module.ts 설정 수정 예시:
```typescript
TypeOrmModule.forRootAsync({
  imports: [ConfigModule],
  inject: [ConfigService],
  useFactory: (configService: ConfigService) => ({
    type: 'postgres',
    host: configService.get('DB_HOST'),
    port: +configService.get<number>('DB_PORT'),
    username: configService.get('DB_USER'),
    password: configService.get('DB_PASSWORD'),
    database: configService.get('DB_NAME'),
    ssl: {
      rejectUnauthorized: false,  // SSL을 강제할 경우 필요
    },
    entities: [Music, User, Post],
    synchronize: true,
  }),
}),
```
### 4. RDS 파라미터 그룹에서 SSL 설정 확인
AWS RDS 콘솔에서 RDS 인스턴스의 파라미터 그룹을 확인하고, SSL이 강제되어 있는지 확인합니다. 만약 강제되어 있다면, 백엔드에서 SSL 연결을 설정해야 합니다.
### 5. 환경 변수 확인
RDS 설정에서 지정한 데이터베이스 정보가 .env 파일에 올바르게 입력되었는지 확인합니다.

**Comment by LyleSeungju** [comment]
확인 결과 
RDS에서는 엔드 포인트는 정상 작동하나, Nest.js에서 PostgreSQL를 실행시킬때 의도치 않게 SSL 설정이 된 것을 확인했습니다.
그래서 Nest.js에서 SSL 사용을 비활성화하게끔 설정하였고 정상 작동을 확인했습니다.
